language: node_js
dist: focal
node_js:
  - 18
# Need a C++ compiler
addons:
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @lhci/cli@0.9.x
  - npm install -g webpack@5.67.0
  - npm install -g webpack-cli@4.10.0
  - npm install -g npm@9.8.1
install:
  - npm install --legacy-peer-deps --timeout=90000
script:
  - npm run dev
  - npm run travis
  - npm run lhci:audit
  - npm run lhci:desktop
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
